### ISSUE TITLE
建议合并 https://mirrors.nju.edu.cn/help/ 和 https://nju-mirror-help.njuer.org/

### ISSUE THREAD

**Issue by ykla** [nju-lug/Mira#16]
二者存在教程不一致的情况，且重复了，应该予以更正合并。如 `https://nju-mirror-help.njuer.org/`  包含 FreeBSD、FreeBSD-pkg、FreeBSD-ports 等使用方法，而 `https://mirrors.nju.edu.cn/help/` 却没有。

推荐在合并`https://nju-mirror-help.njuer.org/`的基础上，保留首页的 `https://mirrors.nju.edu.cn/help/`.

**Comment by iori2333** [comment]
这个网站并不是我们负责的（虽然GitHub账户名叫njulug），因此我们也无权合并。上面的帮助有一些已经年久失修，目前的帮助是从tuna参考而来的。
