### ISSUE TITLE
kubernetes ubuntu部分版本源为空

### ISSUE THREAD

**Issue by wuooyun** [nju-lug/Mira#26]
https://mirrors.nju.edu.cn/help/kubernetes
按照帮助手册，ubuntu18.04 20.04版本源在更新时提示404。
无效源
deb https://mirror.nju.edu.cn/kubernetes/apt kubernetes-focal main

**Comment by d-w-x** [comment]
抱歉，已经按照[清华大学的使用说明](https://mirrors.tuna.tsinghua.edu.cn/help/kubernetes/)在同步更新本站说明。

感谢您的及时反馈。
