### ISSUE TITLE
南大源conda无法安装最新版pytorch

### ISSUE THREAD

**Issue by Tony-HYX** [nju-lug/Mira#28]
最新版pytorch安装指令是 `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`，但南大源没有找不到`nvidia` channel，默认源是能安装成功的。

**Comment by LyndonKong** [comment]
由于nvidia license限制，我们已经发送邮件联系。再没有得到进一步的回复之前不会增加 anaconda 的nvidia channel。

**Comment by LyndonKong** [comment]
可以考虑不需要nvidia channel的[previous version](https://pytorch.org/get-started/previous-versions/)。

**Comment by Tony-HYX** [comment]
好的多谢，辛苦了！
