### ISSUE TITLE
bioconductor源是不是不支持低版本的BiocVersion了，比如3.10版本，对应的R版本是3.6.3

### ISSUE THREAD

**Issue by Le-dawn** [nju-lug/Mira#29]
错误信息如下：

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> BiocManager::install("version"="3.10")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://mirrors.bfsu.edu.cn/CRAN/

Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/bioc/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/workflows/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/workflows/src/contrib/PACKAGES'
Bioconductor version 3.10 (BiocManager 1.30.15), R 3.6.3 (2020-02-29)
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/bioc/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirror.nju.edu.cn/bioconductor/packages/3.10/workflows/src/contrib:
  cannot open URL 'https://mirror.nju.edu.cn/bioconductor/packages/3.10/workflows/src/contrib/PACKAGES'
Old packages: 'aroma.core', 'BiocManager', 'bit', 'Cairo', 'data.table',
  'ggpubr', 'magic', 'markdown', 'Matrix', 'modelr', 'pbapply', 'pkgload',
  'plyr', 'R.utils', 'rbibutils', 'roxygen2', 'vctrs', 'xfun'
Update all/some/none? [a/s/n]: n
> 

我直接访问错误提示给出的链接，会出现“404 Not Found”。将其中的3.10改为最新的3.16，可以正常访问

**Comment by yaoge123** [comment]
上游的官方源把老版本删掉了

**Comment by Le-dawn** [comment]
> 上游的官方源把老版本删掉了

现在想要安装老版本的bioconductor包是不是只能从官方源获取了

**Comment by d-w-x** [comment]
抱歉，只能由您自行寻找支持对应版本的源。这边是无法支持了。
