### ISSUE TITLE
为什么最近安装pytorch时默认都是cpu版本，之前用南大镜像的时候是正常的

### ISSUE THREAD

**Issue by lukerluker** [nju-lug/Mira#30]
conda install pytorch torchvision torchaudio cudatoolkit=11.3
就这个指令

**Comment by d-w-x** [comment]
最新版本Stable (1.13.1)的 pytorch 安装命令发生了变化，目前 nvidia conda 源由于许可原因我们无法镜像，还望了解。

关于更多内容，您可以到 pytorch 官方网站了解：https://pytorch.org/get-started/locally/
