### ISSUE TITLE
[MFR] Mirror Front End Error Report前端文字显示错误

### ISSUE THREAD

**Issue by LuShengbai** [nju-lug/Mira#39]
## Note

- [x] I understand that the issue raised here **is** related to the **front-end**.
- [x] I understand that the issue raised here **is not** related to the **docmuent or files**.
- [x] I have looked it up in opening issue, it's **not** reported by others.
- [x] I have looked it up in closed issue, it's **not refused** for some reasons.

## Error Information

南哪课表  => 南大课表
![image](https://github.com/nju-lug/Mira/assets/39186040/7778c15c-9d2d-455e-96f0-f401e96af994)

## Other Information

- os with version [操作系统及版本]: 
- browser with version [浏览器及版本]: 
- appear time [大致出现问题的时间]:

**Comment by iori2333** [comment]
这不是一个错误，参见南哪课表[官网](https://nju.app/)。
